organization/urls.py
from django.conf.urls import url, include

from . import views
from .views import (MyOrganizationView, MyOrganizationEditView, MyOrganizationHistoryView,
                    MemberListView, MemberDetailView, MemberAddView, MemberEditView, MemberDeleteView,
                    MessageListView, MessagePostView, MessageDetailView, MessageEditView, MessageDeleteView, MessageStickView, CommentEditView, CommentDeleteView, download_message_attachment)

urlpatterns = [
    url(r'^$', MyOrganizationView.as_view(), name='myorganization'),
    url(r'^edit/$', MyOrganizationEditView.as_view(), name='myorganization_edit'),
    url(r'^history/$', MyOrganizationHistoryView.as_view(), name='myorganization_history'),
    url(r'^members/', include([
        url(r'^list/$', MemberListView.as_view(), name='organization_members_list'),
        url(r'^add/$', MemberAddView.as_view(), name='organization_members_add'),

        url(r'^(?P<member_pk>\d+)/', include([
            url(r'^$', MemberDetailView.as_view(), name='organization_members_view'),
            url(r'^edit/$', MemberEditView.as_view(), name='organization_members_edit'),
            url(r'^delete/$', MemberDeleteView.as_view(), name='organization_members_delete'),
        ])),
    ])),
    url(r'^messages/', include([
        url(r'^list/$', MessageListView.as_view(), name='organization_messages_list'),
        url(r'^post/$', MessagePostView.as_view(), name='organization_messages_post'),

        url(r'^(?P<message_pk>\d+)/', include([
            url(r'^$', MessageDetailView.as_view(), name='organization_messages_view'),
            url(r'^edit/$', MessageEditView.as_view(), name='organization_messages_edit'),
            url(r'^delete/$', MessageDeleteView.as_view(), name='organization_messages_delete'),
            url(r'^quick_stick/$', MessageStickView.as_view(), name='organization_messages_quick_stick'),
            url(r'^download/(?P<attachment_pk>\d+)/$', download_message_attachment, name='organization_messages_download_attachment'),
            url(r'^(?P<comment_pk>\d+)/', include([
                url(r'^edit/$', CommentEditView.as_view(), name='organization_messages_comments_edit'),
                url(r'^delete/$', CommentDeleteView.as_view(), name='organization_messages_comments_delete'),
            ])),
        ])),
    ]))
]

pm/urls.py
from django.conf.urls import url, include

from .views import (PMListView,
                    StartConversationView, ConversationView)

urlpatterns = [
    url(r'^$', PMListView.as_view(), name='pm_list'),
    url(r'^add/$', StartConversationView.as_view(), name='pm_start_conversation'),
    url(r'^(?P<conversation_pk>\d+)/', include([
        url(r'^$', ConversationView.as_view(), name='pm_conversation'),
        url(r'^answer/$', PMListView.as_view(), name='pm_conversation_answer'),
        url(r'^toggle-hidden/$', PMListView.as_view(), name='pm_conversation_toggle_hidden'),
    ])),
]

projectak/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import permission; permission.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^', include('home.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^organization/', include('organization.urls')),
    url(r'^pm/', include('pm.urls')),
    url(r'^notifications/', include('notification.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

message/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Attachment(models.Model):

    class Meta:
        abstract = True
        verbose_name = _("Attachment")
        verbose_name_plural = _("Attachments")


    name = models.CharField(_("name"), max_length=255)
    date = models.DateTimeField(_("Date"), auto_now_add=True)

    # Implement this method to return SENDFILE_ROOT . model_unique_name . pk . filename
    # def file_path(instance, filename):
    #     from projectak.settings import SENDFILE_ROOT
    #     return '{}default/{}/{}'.format(SENDFILE_ROOT, instance.pk, filename)
    #
    # file = models.FileField(upload_to=file_path)


class Message(models.Model):

    class Meta:
        abstract = True
        verbose_name = _("Message")
        verbose_name_plural = _("Messages")
        ordering = ['-sticky', '-date']

    sticky = models.BooleanField(_("Sticky message?"), default=False)
    pinned_members = models.ManyToManyField(
        "organization.Contact",
        verbose_name=_("Pinned members"),
        related_name="%(app_label)s_messages_as_pinned",
        blank=True,
    )

    author = models.ForeignKey("organization.Contact", related_name="%(app_label)s_messages_as_author")
    title = models.CharField(_("Title"), max_length=255)
    date = models.DateTimeField(_("Date"), auto_now_add=True)
    edit_date = models.DateTimeField(_("Date"), auto_now=True)

    body = models.TextField(_("Your message"))

    # attachments

    def get_comment_page(self, comment):
        position = 0
        for comment_db in self.comment_set.all():
            position += 1
            if comment_db == comment:
                break

        import math
        return math.ceil(position / 10)

    allow_comments = models.BooleanField(_("Allow comments?"), default=True)

class Comment(models.Model):

    class Meta:
        abstract = True
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['date']

    # CHILD CLASS : message FK

    author = models.ForeignKey("organization.Contact", related_name="%(app_label)s_comments")
    body = models.TextField(_("Your message"))
    date = models.DateTimeField(_("Date"), auto_now_add=True)
    edit_date = models.DateTimeField(_("Date"), auto_now=True)

    # attachments

message/views.py
from django.shortcuts import render

# Create your views here.

organization/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404

from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from projectak.decorators.permission_required import permission_required

class MyOrganizationViewBase:
    def get_organization(self):
        return self.request.user.contact.organization

    def get_context_data(self, **kwargs):
        context = super(MyOrganizationViewBase, self).get_context_data(**kwargs)

        context['organization'] = self.get_organization()

        return context


class MyOrganizationView(MyOrganizationViewBase, TemplateView):
    template_name = "organization/myorganization/home.html"

    def get_context_data(self, **kwargs):
        context = super(MyOrganizationView, self).get_context_data(**kwargs)

        stickyQueryset = self.get_organization().message_set.filter(sticky=True)
        nonStickyQueryset = self.get_organization().message_set.filter(sticky=False)[:5]
        queryset = (stickyQueryset | nonStickyQueryset)[:max(5, stickyQueryset.count())]

        context['messages'] = queryset.all()

        return context

@permission_required('organization.change_organization')
class MyOrganizationEditView(MyOrganizationViewBase, UpdateView):
    from .models import Organization
    model = Organization
    from .forms import OrganizationForm
    form_class = OrganizationForm

    template_name = "organization/myorganization/edit.html"
    context_object_name = "organization"

    from django.core.urlresolvers import reverse_lazy
    success_url = reverse_lazy('myorganization')

    def get_object(self, queryset=None):
        return self.get_organization()


class MyOrganizationHistoryView(MyOrganizationViewBase, TemplateView):
    template_name = "organization/myorganization/history.html"

    def get_context_data(self, **kwargs):
        from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

        context = super(MyOrganizationHistoryView, self).get_context_data(**kwargs)

        entries = self.get_organization().history_set.all()

        paginator = Paginator(entries, 25)
        page = self.request.GET.get('page')
        try:
            entries = paginator.page(page)
        except PageNotAnInteger:
            entries = paginator.page(1)
        except EmptyPage:
            entries = paginator.page(paginator.num_pages)


        context['entries'] = entries

        return context


# Members
@permission_required('organization.manage_members_organization')
class MemberAddView(MyOrganizationViewBase, CreateView):
    from .models import Contact
    model = Contact
    from .forms import ContactAddForm
    form_class = ContactAddForm

    template_name = "organization/members/add.html"

    def form_valid(self, form):
        form.set_organization(self.get_organization())
        member = form.save()
        return super(MemberAddView, self).form_valid(form)

    def get_success_url(self):
        from django.core.urlresolvers import reverse_lazy
        return reverse_lazy('organization_members_list')

#@permission_required('organization.manage_members_organization')
class MemberListView(MyOrganizationViewBase, ListView):
    from .models import Contact
    model = Contact
    context_object_name = 'contacts'

    template_name = "organization/members/list.html"

    def get_queryset(self):
        return self.get_organization().get_members()

# @permission_required('organization.manage_members_organization')
class MemberDetailView(MyOrganizationViewBase, DetailView):
    pk_url_kwarg = "member_pk"
    from .models import Contact
    model=Contact

    template_name = "organization/members/view.html"
    context_object_name = "member"

@permission_required('organization.manage_members_organization')
class MemberEditView(UserPassesTestMixin, MyOrganizationViewBase, UpdateView):
    pk_url_kwarg = "member_pk"

    from .models import Contact
    model = Contact
    from .forms import ContactForm
    form_class = ContactForm

    def form_valid(self, form):
        form.set_organization(self.get_organization())
        member = form.save()
        return super(MemberEditView, self).form_valid(form)

    template_name = "organization/members/edit.html"
    context_object_name = "member"


    raise_exception = True
    def test_func(self):
        return self.request.user.contact != self.get_object()


@permission_required('organization.manage_members_organization')
class MemberDeleteView(UserPassesTestMixin, MyOrganizationViewBase, DeleteView):
    pk_url_kwarg = "member_pk"

    from .models import Contact
    model = Contact

    template_name = "organization/members/delete.html"
    context_object_name = "member"

    def get_success_url(self):
        from django.core.urlresolvers import reverse_lazy
        return reverse_lazy('organization_members_list')

    raise_exception = True
    def test_func(self):
        return self.request.user.contact != self.get_object()



# Messages
class MessagePostView(MyOrganizationViewBase, CreateView):
    from .models import Message
    model = Message
    from .forms import MessageForm
    form_class = MessageForm

    template_name = "organization/messages/post.html"

    def form_valid(self, form):
        form.instance.organization = self.get_organization()
        form.instance.author = self.request.user.contact

        return super(MessagePostView, self).form_valid(form)

    def get_success_url(self):
        from django.core.urlresolvers import reverse_lazy
        return reverse_lazy('organization_messages_list')


    def get_context_data(self, **kwargs):
        context = super(MessagePostView, self).get_context_data(**kwargs)

        context['form'].fields['pinned_members'].queryset = self.request.user.contact.organization.get_members()

        return context

@permission_required('organization.change_message')
class MessageEditView(MyOrganizationViewBase, UpdateView):
    pk_url_kwarg = "message_pk"

    from .models import Message
    model = Message
    from .forms import MessageForm
    form_class = MessageForm

    template_name = "organization/messages/edit.html"
    context_object_name = "message"


    def get_context_data(self, **kwargs):
        context = super(MessageEditView, self).get_context_data(**kwargs)

        context['form'].fields['pinned_members'].queryset = self.request.user.contact.organization.get_members()

        return context

@permission_required('organization.delete_message')
class MessageDeleteView(MyOrganizationViewBase, DeleteView):
    pk_url_kwarg = "message_pk"

    from .models import Message
    model = Message

    template_name = "organization/messages/delete.html"
    context_object_name = "message"

    def get_success_url(self):
        from django.core.urlresolvers import reverse_lazy
        return reverse_lazy('organization_messages_list')


class MessageListView(MyOrganizationViewBase, ListView):
    from .models import Message
    model = Message
    context_object_name = 'messages'

    template_name = "organization/messages/list.html"


    def get_context_data(self, **kwargs):
        from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

        context = super(MessageListView, self).get_context_data(**kwargs)

        messages = self.get_queryset()

        paginator = Paginator(messages, 10)
        page = self.request.GET.get('page')
        try:
            messages = paginator.page(page)
        except PageNotAnInteger:
            messages = paginator.page(1)
        except EmptyPage:
            messages = paginator.page(paginator.num_pages)

        context['messages'] = messages

        return context


    def get_queryset(self):
        return self.get_organization().message_set.all()

from .forms import CommentForm
class MessageDetailView(MyOrganizationViewBase, DetailView):
    pk_url_kwarg = "message_pk"
    from .models import Message
    model=Message

    template_name = "organization/messages/view.html"
    context_object_name = "message"


    def get_context_data(self, **kwargs):
        from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

        context = super(MessageDetailView, self).get_context_data(**kwargs)

        comments = self.get_object().comment_set.all()

        paginator = Paginator(comments, 10)
        page = self.request.GET.get('page')
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)

        context['comments'] = comments
        context['form_quick_answer'] = CommentForm()

        return context

    def post(self, request, *args, **kwargs):
        if not self.get_object().allow_comments:
            from django.core.exceptions import PermissionDenied
            raise PermissionDenied

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)

            comment.message = self.get_object()

            comment.author = request.user.contact
            import datetime
            comment.date = datetime.datetime.now()

            comment.save()

            return redirect('{}?page={}#comment-{}'.format(reverse('organization_messages_view', kwargs={'message_pk':self.get_object().pk}), comment.message.get_comment_page(comment), comment.pk))

        return render(request, self.template_name, {'form_quick_answer': form})

# will return 404 if not orgnization member because of organization__pk
def download_message_attachment(request, message_pk, attachment_pk):
    from .models import Attachment

organization/templates/organization/messages/comment_delete.html
{% extends "organization_base.html" %}
{% load i18n %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
<a href="{% url 'organization_messages_view' message_pk=comment.message.pk %}" class="breadcrumb">{{ comment.message.title }}</a>
<a href="{% url 'organization_messages_comments_delete' message_pk=comment.message.pk comment_pk=comment.pk %}" class="breadcrumb">{% trans "Delete my comment" %}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>
    {{ message.title }}

    <small>
        {% trans "Delete my comment" %}
    </small>
</h1>

<p>
    {% blocktrans %}
    Are you sure you want to delete your comment?
    {% endblocktrans %}
</p>

<div class="card-panel teal lighten-4">
    {{ comment.body|linebreaks }}
</div>

{% include "form/form.html" with form=form submit_color='red' %}
{% endblock body %}

organization/templates/organization/messages/comment_edit.html
{% extends "organization_base.html" %}
{% load i18n %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
<a href="{% url 'organization_messages_view' message_pk=comment.message.pk %}" class="breadcrumb">{{ comment.message.title }}</a>
<a href="{% url 'organization_messages_comments_edit' message_pk=comment.message.pk comment_pk=comment.pk %}" class="breadcrumb">{% trans "Edit my comment" %}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>
    {{ message.title }}

    <small>
        {% trans "Edit my comment" %}
    </small>
</h1>

{% include "form/form.html" with form=form %}
{% endblock body %}

organization/templates/organization/messages/delete.html
{% extends "organization_base.html" %}
{% load i18n %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
<a href="{% url 'organization_messages_view' message_pk=message.pk %}" class="breadcrumb">{{ message.title }}</a>
<a href="{% url 'organization_messages_delete' message_pk=message.pk %}" class="breadcrumb">{% trans "Delete" %}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>
    {{ message.title }}

    <small>
        {% trans "Delete" %}
    </small>
</h1>

<p>
    {% blocktrans with message=message.title %}
    Are you sure you want to delete your message "{{ message }}", along with all its attachments and comments?
    {% endblocktrans %}
</p>

{% include "form/form.html" with form=form submit_color='red' %}
{% endblock body %}

organization/templates/organization/messages/edit.html
{% extends "organization_base.html" %}
{% load i18n %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
<a href="{% url 'organization_messages_view' message_pk=message.pk %}" class="breadcrumb">{{ message.title }}</a>
<a href="{% url 'organization_messages_edit' message_pk=message.pk %}" class="breadcrumb">{% trans "Edit" %}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>
    {{ message.title }}

    <small>
        {% trans "Edit" %}
    </small>
</h1>

{% include "form/form.html" with form=form file_upload=True %}
{% endblock body %}

organization/templates/organization/messages/list.html
{% extends "organization_base.html" %}
{% load i18n organization_snippets %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>{% trans "Messages" %}</h1>

<p>
    <a href="{% url 'organization_messages_post' %}" class="btn btn-large yellow darken-4"><i class="material-icons left">message</i> {% trans "Post a message" %}</a>
</p>

{% include "pagination/pagination.html" with paginated_list=messages %}
<table class="striped">
    <thead>
        <tr>
            <th><!-- Sticky --></th>
            <th><!-- Attachment --></th>
            <th>{% trans "Title" %}</th>
            <th>{% trans "Author" %}</th>
            <th>{% trans "Date" %}</th>
            <th>{% trans "Pinned members" %}</th>
        </tr>
    </thead>

    <tbody>
        {% for message in messages %}
        <tr>
            <td>
                {% if message.sticky %}
                <i class="material-icons red-text">announcement</i>
                {% endif %}

                {% if user has "organization.stick_message_organization" of request.user.contact.organization %}
                {% if not message.sticky %}
                <a href="{% url 'organization_messages_quick_stick' message_pk=message.pk %}">
                    <i class="material-icons tiny">check_box_outline_blank</i>
                </a>
                {% else %}
                <a href="{% url 'organization_messages_quick_stick' message_pk=message.pk %}">
                    <i class="material-icons tiny">check_box</i></a>
                </a>
                {% endif %}
                {% endif %}
            </td>
            <td>
                {% if message.attachment_set.all %}
                <i class="material-icons grey-text text-darken-3">attachment</i>
                {% endif %}
            </td>
            <td>
                <strong><a href="{% url "organization_messages_view" message_pk=message.pk %}">{{ message.title }}</a></strong>
            </td>
            <td>
                {% user_chip message.author %}
            </td>
            <td>
                {{ message.date|date:"DATETIME_FORMAT" }}
            </td>
            <td>
                {% for contact in message.pinned_members.all %}
                {% user_chip contact %}
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "pagination/pagination.html" with paginated_list=messages %}
{% endblock body %}

organization/templates/organization/messages/post.html
{% extends "organization_base.html" %}
{% load i18n %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
<a href="{% url 'organization_messages_post' %}" class="breadcrumb">{% trans "Post a message" %}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>
    {% trans "Post a message" %}

    <small>
        {{ organization.name }}
    </small>
</h1>

{% include "form/form.html" with form=form file_upload=True %}
{% endblock body %}

organization/templates/organization/messages/view.html
{% extends "organization_base.html" %}
{% load i18n organization_snippets %}

{% block organization_breadcrumbs %}
<a href="{% url 'organization_messages_list' %}" class="breadcrumb">{% trans "Messages" %}</a>
<a href="{% url 'organization_messages_view' message_pk=message.pk %}" class="breadcrumb">{{ message.title }}</a>
{% endblock organization_breadcrumbs %}

{% block body %}
<h1>
    {{ message.title }}
    <small>
        {{ message.organization.name }}
    </small>
</h1>

{% if user has "organization.change_message" of message %}
<a href="{% url 'organization_messages_edit' message_pk=message.pk %}" class="btn yellow darken-4"><i class="material-icons left">edit</i> {% trans "Edit" %}</a>
{% endif %}
{% if user has "organization.delete_message" of message %}
<a href="{% url 'organization_messages_delete' message_pk=message.pk %}" class="btn red"><i class="material-icons left">delete</i> {% trans "Delete" %}</a>
{% endif %}

<div class="row">
    <div class="col s12 m8">
        {{ message.body|linebreaks }}
    </div>
    <div class="col s12 m4">
        <div class="card-panel">
            {% if message.sticky %}
            <i class="material-icons small red-text">announcement</i>
            <br>
            {% endif %}

            {% trans "Posted by" %} {% user_chip message.author %}, {% trans "on" %} {{ message.date|date:"DATETIME_FORMAT" }}

            <br>

            <h5>{% trans "Pinned members" %}</h5>
            {% for contact in message.pinned_members.all %}
            {% user_chip contact %}
            {% empty %}
            {% trans "Nobody" %}
            {% endfor %}

            <h5>{% trans "Attachments" %}</h5>

            <ul class="collection">
                {% for attachment in message.attachment_set.all %}
                <li class="collection-item">
                    <a href="{% url "organization_messages_download_attachment" message_pk=message.pk attachment_pk=attachment.pk %}">
                        <i class="material-icons left">attachment</i>
                        {{ attachment.name }}
                    </a>
                </li>
                {% empty %}
                <li class="collection-item">{% trans "No attachments" %}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<h3>{% trans "Comments" %}</h3>

{% include "pagination/pagination.html" with paginated_list=comments %}
<table class="bordered striped conversation">
    {% for comment in comments %}
    <tr id="comment-{{ comment.pk }}">
        <td>
            {% user_chip comment.author %}
            <hr />
            {{ comment.date|date:"DATE_FORMAT" }} {% trans "at" %} {{ comment.date|date:"TIME_FORMAT" }}
        </td>
        <td>
            {{ comment.body|linebreaks }}

            {% if user has "organization.change_comment" of comment or user has "organization.delete_comment" of comment %}
            <hr>
            {% if user has "organization.change_comment" of comment %}
            <a href="{% url 'organization_messages_comments_edit' message_pk=message.pk comment_pk=comment.pk %}" class="yellow-text text-darken-4">{% trans "Edit" %}</a>
            {% endif %}
            {% if user has "organization.delete_comment" of comment %}
            <a href="{% url 'organization_messages_comments_delete' message_pk=message.pk comment_pk=comment.pk %}" class="red-text">{% trans "Delete" %}</a>
            {% endif %}
            {% endif %}
        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="2">There are no comments.</td>
    </tr>
    {% endfor %}
</table>
{% include "pagination/pagination.html" with paginated_list=comments %}

{% if message.allow_comments %}
<h4>Quick comment</h4>

{% if not comments.has_next %}
{% include "form/form.html" with form=form_quick_answer %}
{% else %}
<p>
    {% trans "You cannot comment from here, because you are not on last page." %}
</p>
{% endif %}
{% else %}
<p>
    {% trans "Comments have been disabled for this message." %}
</p>
{% endif %}
{% endblock body %}