pm/urls.py
from django.conf.urls import url, include

from .views import (PMListView,
                    StartConversationView, ConversationView)

urlpatterns = [
    url(r'^$', PMListView.as_view(), name='pm_list'),
    url(r'^add/$', StartConversationView.as_view(), name='pm_start_conversation'),
    url(r'^(?P<conversation_pk>\d+)/', include([
        url(r'^$', ConversationView.as_view(), name='pm_conversation'),
        url(r'^answer/$', PMListView.as_view(), name='pm_conversation_answer'),
        url(r'^toggle-hidden/$', PMListView.as_view(), name='pm_conversation_toggle_hidden'),
    ])),
]

project/urls.py
from django.conf.urls import url, include

from .views import (ProjectListView, ProjectAddView, ProjectOverviewView, ProjectEditView, ProjectDeleteView, ProjectCloseView, ProjectHistoryView,
    TaskListListView, TaskListAddView, TaskListDetailView, TaskListEditView, TaskListDeleteView, TaskListCopyView, TaskListMoveView, TaskListHistoryView,
    TaskEditView, TaskDeleteView, TaskAddView, TaskCloseView,
    MilestoneListView, MilestoneAddView, MilestoneDetailView, MilestoneEditView, MilestoneDeleteView, MilestoneCloseView, MilestoneHistoryView,
    MessageListView, MessagePostView, MessageDetailView, MessageEditView, MessageDeleteView, MessageStickView, CommentEditView, CommentDeleteView, download_message_attachment)

urlpatterns = [
    url(r'^$', ProjectListView.as_view(), name='projects_list'),
    url(r'^add/$', ProjectAddView.as_view(), name='project_add'),
    url(r'^(?P<project_pk>\d+)/', include([
        url(r'^$', ProjectOverviewView.as_view(), name='project_overview'),
        url(r'^edit/$', ProjectEditView.as_view(), name='project_edit'),
        url(r'^delete/$', ProjectDeleteView.as_view(), name='project_delete'),
        url(r'^check/$', ProjectCloseView.as_view(), name='project_check'),
        url(r'^history/$', ProjectHistoryView.as_view(), name='project_history'),
        url(r'^milestones/', include([
            url(r'^$', MilestoneListView.as_view(), name='project_milestones_list'),
            url(r'^add/$', MilestoneAddView.as_view(), name='project_milestones_add'),
            url(r'^(?P<milestone_pk>\d+)/$', MilestoneDetailView.as_view(), name='project_milestones_view'),
            url(r'^(?P<milestone_pk>\d+)/edit/$', MilestoneEditView.as_view(), name='project_milestones_edit'),
            url(r'^(?P<milestone_pk>\d+)/delete/$', MilestoneDeleteView.as_view(), name='project_milestones_delete'),
            url(r'^(?P<milestone_pk>\d+)/check/$', MilestoneCloseView.as_view(), name='project_milestones_check'),
            url(r'^(?P<milestone_pk>\d+)/quick_check/$', MilestoneCloseView.as_view(), { 'quick': True }, name='project_milestones_quick_check'),
            url(r'^(?P<milestone_pk>\d+)/history/$', MilestoneHistoryView.as_view(), name='project_milestones_history'),
        ])),
        url(r'^task_lists/', include([
            url(r'^list/$', TaskListListView.as_view(), name='project_task_lists_list'),
            url(r'^add/$', TaskListAddView.as_view(), name='project_task_lists_add'),
            url(r'^add/milestone-(?P<milestone_pk>\d+)/$', TaskListAddView.as_view(), name='project_task_lists_add_tomilestone'),

            url(r'^(?P<task_list_pk>\d+)/', include([
                url(r'^$', TaskListDetailView.as_view(), name='project_task_lists_view'),
                url(r'^edit/$', TaskListEditView.as_view(), name='project_task_lists_edit'),
                url(r'^delete/$', TaskListDeleteView.as_view(), name='project_task_lists_delete'),
                url(r'^copy/$', TaskListCopyView.as_view(), name='project_task_lists_copy'),
                url(r'^move/$', TaskListMoveView.as_view(), name='project_task_lists_move'),
                url(r'^history/$', TaskListHistoryView.as_view(), name='project_task_lists_history'),
                url(r'^tasks/', include([
                    url(r'^add/$', TaskAddView.as_view(), name='project_tasks_add'),
                    url(r'^(?P<task_pk>\d+)/edit/$', TaskEditView.as_view(), name='project_tasks_edit'),
                    url(r'^(?P<task_pk>\d+)/delete/$', TaskDeleteView.as_view(), name='project_tasks_delete'),
                    url(r'^(?P<task_pk>\d+)/check/$', TaskCloseView.as_view(), name='project_tasks_check'),
                    url(r'^(?P<task_pk>\d+)/quick_check/$', TaskCloseView.as_view(), { 'quick': True, 'milestone': False }, name='project_tasks_quick_check'),
                    url(r'^(?P<task_pk>\d+)/quick_check_milestone_(?P<milestone_pk>\d+)/$', TaskCloseView.as_view(), { 'quick': True }, name='project_tasks_quick_check_milestone'),
                ])),
            ])),
        ])),
        url(r'^messages/', include([
            url(r'^list/$', MessageListView.as_view(), name='project_messages_list'),
            url(r'^post/$', MessagePostView.as_view(), name='project_messages_post'),

            url(r'^(?P<message_pk>\d+)/', include([
                url(r'^$', MessageDetailView.as_view(), name='project_messages_view'),
                url(r'^edit/$', MessageEditView.as_view(), name='project_messages_edit'),
                url(r'^delete/$', MessageDeleteView.as_view(), name='project_messages_delete'),
                url(r'^quick_stick/$', MessageStickView.as_view(), name='project_messages_quick_stick'),
                url(r'^download/(?P<attachment_pk>\d+)/$', download_message_attachment, name='project_messages_download_attachment'),
                url(r'^(?P<comment_pk>\d+)/', include([
                    url(r'^edit/$', CommentEditView.as_view(), name='project_messages_comments_edit'),
                    url(r'^delete/$', CommentDeleteView.as_view(), name='project_messages_comments_delete'),
                ])),
            ])),
        ]))
    ])),
]

projectak/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import permission; permission.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^', include('home.urls')),
    url(r'^project/', include('project.urls')),
    url(r'^organization/', include('organization.urls')),
    url(r'^pm/', include('pm.urls')),
    url(r'^notifications/', include('notification.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

history/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class History(models.Model):
    class Meta:
        verbose_name = "History entry"
        verbose_name_plural = "History entries"
        ordering = ['-date']

    date = models.DateTimeField(_("Date"), auto_now_add=True)

    contact = models.ForeignKey("organization.Contact")

    TYPE = (
        (_('Organization'), (
            ('organization_organization_updated', _('Organization informations have been updated.')), #O
            ('organization_message_new', _('A message has been published.')), #O
            ('organization_message_deleted', _('A message has been deleted.')), #O
            ('organization_message_sticked', _('A message has been sticked.')), #O
            ('organization_message_comment', _('A comment has been posted.')), #O
            ('organization_member_new', _('Please welcome a new member!')), #O
            ('organization_member_updated', _('Member profile updated.')), #O
            ('organization_member_deleted', _('A member has left us.')), #O
        )),
        (_('Project'), (
            ('project_project_creation', _('Project creation.')), #O|P
            ('project_project_updated', _('Project informations have been updated.')), #P
            ('project_project_deleted', _('A project has been deleted.')), #O
            ('project_project_closed', _('Project has been closed.')), #O|P
            ('project_project_reopened', _('Project has been reopened.')), #O|P

            ('project_milestone_new', _('Milestone creation.')), #P|M
            ('project_milestone_updated', _('Milestone informations have been updated.')), #M
            ('project_tl_milestone_added', _('A task list has been assigned to this milestone.')), #M
            ('project_tl_milestone_deleted', _('Task list has been removed from this milestone.')), #M
            ('project_milestone_closed', _('Milestone has been completed. Congratulations!')), #P|M
            ('project_milestone_reopened', _('Milestone has been reopened.')), #P|M
            ('project_milestone_deleted', _('A milestone has been deleted.')), #P

            ('project_tl_new', _('Task list creation.')), #P|TL
            ('project_tl_updated', _('Task list informations have been updated.')), #TL
            ('project_milestone_tl_added', _('Task list has been assigned to a milestone.')), #TL
            ('project_milestone_tl_deleted', _('Task list has been removed from this milestone.')), #TL
            ('project_tl_closed', _('Task list has been completed. Congratulations!')), #P|TL
            ('project_tl_reopened', _('Task list has been reopened.')), #P|TL
            ('project_tl_deleted', _('A task list has been deleted.')), #P

            ('project_task_new', _('A task has been added.')), #TL
            ('project_task_updated', _('Task informations have been updated.')), #TL
            ('project_task_deleted', _('A task has been deleted.')), #TL
            ('project_task_closed', _('Task has been closed.')), #TL
            ('project_task_reopened', _('Task has been reopened.')), #TL

            ('project_message_new', _('A message has been posted.')), #P
            ('project_message_sticked', _('A message has been sticked.')), #P
            ('project_message_deleted', _('A message has been deleted.')), #P
            ('project_message_comment', _('A comment has been posted.')), #P
        )),
    )

    type = models.CharField(_("Type of notification"), max_length=255, choices=TYPE)

    object_pk = models.IntegerField(_("ID of concerned object"))

    original_object_name = models.CharField(_("Original object name"), max_length=255, blank=True, null=True)

    # not blank IF AND ONLY IF has to appear in this view
    project = models.ForeignKey("project.Project", blank=True, null=True, on_delete=models.SET_NULL)
    milestone = models.ForeignKey("project.Milestone", blank=True, null=True, on_delete=models.SET_NULL)
    tl = models.ForeignKey("project.TaskList", blank=True, null=True, on_delete=models.SET_NULL)
    organization = models.ForeignKey("organization.Organization", blank=True, null=True, on_delete=models.SET_NULL)

    def get_object(self):
        from django.core.exceptions import ObjectDoesNotExist
        try:
            if self.type.startswith('organization_organization'):
                from organization.models import Organization
                return Organization.objects.get(pk=self.object_pk)
            elif self.type.startswith('organization_message'):
                from organization.models import Message
                return Message.objects.get(pk=self.object_pk)
            if self.type.startswith('organization_member'):
                from organization.models import Contact
                return Contact.objects.get(pk=self.object_pk)
            elif self.type.startswith('project_project'):
                from project.models import Project
                return Project.objects.get(pk=self.object_pk)
            elif self.type.startswith('project_milestone'):
                from project.models import Milestone
                return Milestone.objects.get(pk=self.object_pk)
            elif self.type.startswith('project_tl'):
                from project.models import TaskList
                return TaskList.objects.get(pk=self.object_pk)
            elif self.type.startswith('project_task'):
                from project.models import Task
                return Task.objects.get(pk=self.object_pk)
            elif self.type.startswith('project_message'):
                from project.models import Message
                return Message.objects.get(pk=self.object_pk)
        except ObjectDoesNotExist:
            return None

    def get_object_url(self):
        if self.type.startswith('organization_organization'):
            from django.core.urlresolvers import reverse
            return reverse('myorganization')

        return self.get_object().get_absolute_url()

    def get_object_display(self):
        if self.get_object():
            if self.type.startswith('organization_organization'):
                return '{message}'.format(
                    message=self.get_object().name,
                )
            elif self.type.startswith('organization_message'):
                return '{message}'.format(
                    message=self.get_object().title,
                )
            elif self.type.startswith('organization_member'):
                return '{message}'.format(
                    message=self.get_object().user.get_full_name(),
                )
            elif self.type.startswith('project_project'):
                return '{project}'.format(
                    project=self.get_object().name,
                )
            elif self.type.startswith('project_milestone'):
                return '{milestone}'.format(
                    milestone=self.get_object().name,
                )
            elif self.type.startswith('project_tl'):
                return '{tl}'.format(
                    tl=self.get_object().name,
                )
            elif self.type.startswith('project_task'):
                return '{task}'.format(
                    task=self.get_object().name,
                )
            elif self.type.startswith('project_message'):
                return '{message}'.format(
                    message=self.get_object().title,
                )
        else:
            return self.original_object_name

    def make_bindings(self):
        # if special, then it has to be treated special!
        if self.type in ['project_milestone_tl_added', 'project_milestone_tl_deleted', 'project_tl_milestone_added', 'project_tl_milestone_deleted']:
            return


        elif self.type.startswith('organization_organization'):
            self.organization = self.get_object()
        elif self.type.startswith('organization_message'):
            self.organization = self.get_object().organization
        elif self.type.startswith('organization_member'):
            self.organization = self.get_object().organization

        elif self.type.startswith('project_project_') and not self.type.endswith('_updated'):
            self.organization = self.get_object().organization
            self.project = self.get_object()
        elif self.type.startswith('project_project_'):
            self.project = self.get_object()


        elif self.type.startswith('project_milestone_') and not (self.type.endswith('_updated') or self.type.endswith('_tl')):
            self.project = self.get_object().project
            self.milestone = self.get_object()
        elif self.type.startswith('project_milestone_'):
            self.milestone = self.get_object()


        elif self.type.startswith('project_tl_') and not self.type.endswith('_updated'):
            self.project = self.get_object().project
            self.tl = self.get_object()
        elif self.type.startswith('project_tl_'):
            self.tl = self.get_object()


        elif self.type.startswith('project_task_'):
            self.tl = self.get_object().task_list


        elif self.type.startswith('project_message_'):
            self.project = self.get_object().project

history/views.py
from django.shortcuts import render

# Create your views here.

project/templates/project/milestones/add.html
{% extends "project_base.html" %}
{% load i18n %}

{% block project_breadcrumbs %}
<a href="{% url 'project_milestones_list' project_pk=project.pk %}" class="breadcrumb">{% trans "Milestones" %}</a>
<a href="{% url 'project_milestones_add' project_pk=project.pk %}" class="breadcrumb">{% trans "Add a milestone" %}</a>
{% endblock project_breadcrumbs %}

{% block body %}
<h1>
    {% trans "Add a milestone" %}

    <small>
        {{ project.name }}
    </small>
</h1>

{% include "form/form.html" with form=form %}
{% endblock body %}

project/templates/project/milestones/delete.html
{% extends "project_base.html" %}
{% load i18n %}

{% block project_breadcrumbs %}
<a href="{% url 'project_milestones_list' project_pk=project.pk %}" class="breadcrumb">{% trans "Milestones" %}</a>
<a href="{% url 'project_milestones_view' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{{ milestone.name }}</a>
<a href="{% url 'project_milestones_delete' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{% trans "Delete" %}</a>
{% endblock project_breadcrumbs %}

{% block body %}
<h1>
    {{ milestone.name }}

    <small>
        {% trans "Delete" %}
    </small>
</h1>

<p>
    {% blocktrans with milestone=milestone.name %}
    Are you sure you want to delete the milestone "{{ milestone }}" ? (It will not delete the assigned task lists)
    {% endblocktrans %}
</p>

{% include "form/form.html" with submit_color='red' %}
{% endblock body %}

project/templates/project/milestones/edit.html
{% extends "project_base.html" %}
{% load i18n %}

{% block project_breadcrumbs %}
<a href="{% url 'project_milestones_list' project_pk=project.pk %}" class="breadcrumb">{% trans "Milestones" %}</a>
<a href="{% url 'project_milestones_view' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{{ milestone.name }}</a>
<a href="{% url 'project_milestones_edit' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{% trans "Edit" %}</a>
{% endblock project_breadcrumbs %}

{% block body %}
<h1>
    {{ task.name }}

    <small>
        {% trans "Edit" %}
    </small>
</h1>

{% include "form/form.html" with form=form %}
{% endblock body %}

project/templates/project/milestones/history.html
{% extends "project_base.html" %}
{% load i18n %}

{% block project_breadcrumbs %}
<a href="{% url 'project_milestones_list' project_pk=project.pk %}" class="breadcrumb">{% trans "Milestones" %}</a>
<a href="{% url 'project_milestones_view' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{{ milestone.name }}</a>
<a href="{% url 'project_milestones_history' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{% trans "History" %}</a>
{% endblock project_breadcrumbs %}

{% block body %}
<h1>
    {{ milestone.name }}

    <small>
        {% trans "History" %}
    </small>
</h1>

{% include "pagination/pagination.html" with paginated_list=entries %}
{% include "history/_table.html" with entries=entries %}
{% include "pagination/pagination.html" with paginated_list=entries %}
{% endblock body %}

project/templates/project/milestones/list.html
{% extends "project_base.html" %}
{% load i18n %}

{% block project_breadcrumbs %}
<a href="{% url 'project_milestones_list' project_pk=project.pk %}" class="breadcrumb">{% trans "Milestones" %}</a>
{% endblock project_breadcrumbs %}

{% block body %}
<h1>{% trans "Milestones" %}</h1>

{% if user has "project.add_milestone_project" of project %}
<p>
    <a href="{% url 'project_milestones_add' project_pk=project.pk %}" class="btn amber accent-4"><i class="material-icons left">add</i> {% trans "Add" %}</a>
</p>
{% endif %}

<table class="striped">
    <thead>
        <tr>
            <th></th>
            <th>{% trans "Due date" %}</th>
            <th>{% trans "Name" %}</th>
            <th>{% trans "Days left" %}</th>
        </tr>
    </thead>

    <tbody>
        {% for milestone in project.milestone_set.all %}
        <tr>
            <td>
                {% if user has "project.close_milestone" of milestone %}
                <a href="{% url 'project_milestones_quick_check' project_pk=project.pk milestone_pk=milestone.pk %}">
                {% endif %}
                    {% if milestone.closed %}
                    <i class="material-icons green-text">check_box</i></a>
                    {% else %}
                    <i class="material-icons orange-text">check_box_outline_blank</i>
                    {% endif %}
                {% if user has "project.close_milestone" of milestone %}
                </a>
                {% endif %}
            </td>
            <td>{{ milestone.due_date|date:"DATE_FORMAT" }}</td>
            <td>
                <a href="{% url 'project_milestones_view' project_pk=project.pk milestone_pk=milestone.pk %}">{{ milestone.name }}</a>
            </td>
            <td>
                {% if not milestone.closed %}
                {% if not milestone.getLate %}
                {% blocktrans with daysLeft=milestone.getDaysDiffFromToday %}
                {{ daysLeft }} days left
                {% endblocktrans %}
                {% else %}
                {% blocktrans with daysLeft=milestone.getDaysDiffFromToday %}
                {{ daysLeft }} days late
                {% endblocktrans %}
                {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock body %}

project/templates/project/milestones/view.html
{% extends "project_base.html" %}
{% load i18n project_snippets organization_snippets %}

{% block project_breadcrumbs %}
<a href="{% url 'project_milestones_list' project_pk=project.pk %}" class="breadcrumb">{% trans "Milestones" %}</a>
<a href="{% url 'project_milestones_view' project_pk=project.pk milestone_pk=milestone.pk %}" class="breadcrumb">{{ milestone.name }}</a>
{% endblock project_breadcrumbs %}

{% block body %}
<div class="card-panel right" style="max-width: 40%;">
    {% progress milestone %}

    {{ milestone.description|linebreaks }}
</div>
<h1>
    {{ milestone.name }}

    <small>
        {% trans "Milestone" %}

        <span class="chip {% if milestone.closed %}light-green{% else %}orange{% endif %}">
            {% if milestone.closed %}
            {% blocktrans with closed_date=milestone.closed_date|date:"DATE_FORMAT" %}
            Completed on {{ closed_date }}
            {% endblocktrans %}
            {% else %}
            {% trans "Open" %}
            {% endif %}
        </span>

        <span class="chip">
            {{ milestone.due_date|date:"DATE_FORMAT" }}

            {% if not milestone.closed %}
            {% if not milestone.getLate %}
            {% blocktrans with daysLeft=milestone.getDaysDiffFromToday %}
            ({{ daysLeft }} days left)
            {% endblocktrans %}
            {% else %}
            {% blocktrans with daysLeft=milestone.getDaysDiffFromToday %}
            ({{ daysLeft }} days late)
            {% endblocktrans %}
            {% endif %}
            {% endif %}
        </span>
    </small>
</h1>


<p>
    {% if user has "project.change_milestone" of milestone %}
    <a class="btn" href="{% url 'project_milestones_edit' project_pk=project.pk milestone_pk=milestone.pk %}">
        <i class="material-icons left">edit</i>{% trans "Edit" %}
    </a>
    {% endif %}

    {% if user has "project.close_milestone" of milestone %}
    <a class="btn green" href="{% url 'project_milestones_check' project_pk=project.pk milestone_pk=milestone.pk %}">
        {% if milestone.closed %}
        <i class="material-icons left">check_box</i>{% trans "Reopen" %}
        {% else %}
        <i class="material-icons left">check_box_outline_blank</i>{% trans "Mark as completed" %}
        {% endif %}
    </a>
    {% endif %}

    {% if user has "project.delete_milestone" of milestone %}
    <a class="btn red" href="{% url 'project_milestones_delete' project_pk=project.pk milestone_pk=milestone.pk %}">
        <i class="material-icons left">delete</i>{% trans "Delete" %}
    </a>
    {% endif %}
</p>

{% if user has "project.add_task_list_project" of project %}
<p>
    <a href="{% url 'project_task_lists_add_tomilestone' project_pk=project.pk milestone_pk=milestone.pk %}" class="btn waves-effect waves-light amber accent-4"><i class="material-icons left">add</i> {% trans "Add a task list" %}</a>
</p>
{% endif %}

<div class="row">
    <div class="col m9">
        {% for task_list in milestone.getOpenTaskLists %}
        <div id="tasklist_{{ task_list.pk }}" class="section">
            <h4>
                <a href="{% url 'project_task_lists_view' project_pk=project.pk task_list_pk=task_list.pk %}">{{ task_list.name }}</a>

                <span class="normal chip orange">
                    {% trans "Open" %}
                </span>

                {% if task_list.milestone %}
                <span class="normal chip">
                    <a href="{% url 'project_milestones_view' project_pk=project.pk milestone_pk=task_list.milestone.pk %}"><i class="left material-icons">flag</i> {{ task_list.milestone.name }}</a>
                </span>
                {% endif %}

                {% if task_list.due_date %}
                <span class="normal chip">
                    {{ task_list.due_date|date:"DATE_FORMAT" }}

                    {% if not task_list.getLate %}
                    {% blocktrans with daysLeft=task_list.getDaysDiffFromToday %}
                    ({{ daysLeft }} days left)
                    {% endblocktrans %}
                    {% else %}
                    {% blocktrans with daysLeft=task_list.getDaysDiffFromToday %}
                    ({{ daysLeft }} days late)
                    {% endblocktrans %}
                    {% endif %}
                </span>
                {% endif %}
            </h4>

            {{ task_list.description|linebreaks }}

            {% for task in task_list.getTasks %}
            <div id="task_{{ task.pk }}" class="card {% if not task.closed %}blue-grey{% else %}green darken-3{% endif %} white-text">
                <div class="card-content">
                    {% if user has "project.view_members_task" of task %}
                    <span class="right">
                    {% for member in task.members.all %}
                    {% user_chip member %}
                    {% endfor %}
                    </span>
                    {% endif %}

                    <p>
                        {% if user has "project.close_task" of task %}
                        {% if not task.closed %}
                        <a class="light-green-text text-lighten-1" href="{% if task_list_view %}{% url 'project_tasks_check' project_pk=project.pk task_list_pk=task_list.pk task_pk=task.pk %}{% else %}{% url 'project_tasks_quick_check' project_pk=project.pk task_list_pk=task_list.pk task_pk=task.pk %}{% endif %}">
                            <i class="material-icons vam">check_box_outline_blank</i>
                        </a>
                        {% else %}
                        <a class="white-text" href="{% if task_list_view %}{% url 'project_tasks_check' project_pk=project.pk task_list_pk=task_list.pk task_pk=task.pk %}{% else %}{% url 'project_tasks_quick_check' project_pk=project.pk task_list_pk=task_list.pk task_pk=task.pk %}{% endif %}">
                            <i class="material-icons vam">check_box</i></a>
                        </a>
                        {% endif %}
                        {% endif %}

                        <span class="card-title {% if user has "project.change_task" of task or user has "project.delete_task" of task %}activator{% endif %}">{{ task.name }}</span>

                        {% if task.due_date %}
                        <span class="normal italic">
                            {{ task.due_date|date:"DATE_FORMAT" }}

                            {% if not task.closed %}
                            {% if not task.getLate %}
                            {% blocktrans with daysLeft=task.getDaysDiffFromToday %}
                            ({{ daysLeft }} days left)
                            {% endblocktrans %}
                            {% else %}
                            {% blocktrans with daysLeft=task.getDaysDiffFromToday %}
                            ({{ daysLeft }} days late)
                            {% endblocktrans %}
                            {% endif %}
                            {% else %}
                            {% blocktrans with closed_date=task.closed_date|date:"DATE_FORMAT" %}
                            (Closed on {{ closed_date }})
                            {% endblocktrans %}
                            {% endif %}
                        </span>
                        {% endif %}
                    </p>

                    {% if user has "project.change_task" of task or user has "project.delete_task" of task %}
                    <div class="activator">
                    {% endif %}
                        {{ task.description|linebreaks }}
                    {% if user has "project.change_task" of task or user has "project.delete_task" of task %}
                    </div>
                    {% endif %}
                </div>

                {% if user has "project.change_task" of task or user has "project.delete_task" of task %}
                <div class="card-reveal card-actions {% if not task.closed %}blue-grey{% else %}green darken-3{% endif %} white-text">
                    <p>
                        <span class="card-title">{{ task.name }}</span>
                    </p>

                    <p>
                        {% if user has "project.change_task" of task %}
                        <a class="btn" href="{% url 'project_tasks_edit' project_pk=project.pk task_list_pk=task_list.pk task_pk=task.pk %}">{% trans "Edit" %}</a>
                        {% endif %}
                        {% if user has "project.delete_task" of task %}
                        <a class="btn red-text text-darken-3" href="{% url 'project_tasks_delete' project_pk=project.pk task_list_pk=task_list.pk task_pk=task.pk %}">{% trans "Delete" %}</a>
                        {% endif %}
                    </p>
                </div>
                {% endif %}
            </div>
            {% empty %}
            {% trans "No tasks." %}
            {% endfor %}
        </div>

        <div class="divider"></div>
        {% empty %}
        {% trans "No task list." %}
        {% endfor %}
    </div>

    <div class="col m3">
        <h4>{% trans "Completed" %}</h4>
        {% for task_list in milestone.getCompletedTaskLists %}

        <p class="section">
            <a href="{% url 'project_task_lists_view' project_pk=project.pk task_list_pk=task_list.pk %}">{{ task_list.name }}</a><br />
            <span class="italic">
                {% blocktrans with closed_date=task_list.closed_date|date:"DATE_FORMAT" %}
                Closed on {{ closed_date }}
                {% endblocktrans %}
            </span>
        </p>
        {% empty %}
        {% trans "No task list." %}
        {% endfor %}
    </div>
</div>

<h4>
    {% trans "Recent activity" %}
    <a href="{% url 'project_milestones_history' project_pk=project.pk milestone_pk=milestone.pk %}" class="btn-floating waves-effect waves-light light-blue"><i class="material-icons">list</i></a>
</h4>

{% include "history/_table.html" with entries=milestone.history_set.all|slice:":10" %}
{% endblock body %}